# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = D:\Daniel\resources\Code\Hot_words_count

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = D:\Daniel\resources\Code\Hot_words_count\build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start D:\Daniel\resources\Code\Hot_words_count\build\CMakeFiles D:\Daniel\resources\Code\Hot_words_count\build\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start D:\Daniel\resources\Code\Hot_words_count\build\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hotwords

# Build rule for target.
hotwords: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 hotwords
.PHONY : hotwords

# fast build rule for target.
hotwords/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hotwords.dir\build.make CMakeFiles/hotwords.dir/build
.PHONY : hotwords/fast

#=============================================================================
# Target rules for targets named info

# Build rule for target.
info: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 info
.PHONY : info

# fast build rule for target.
info/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\info.dir\build.make CMakeFiles/info.dir/build
.PHONY : info/fast

scripts/main.obj: scripts/main.cpp.obj
.PHONY : scripts/main.obj

# target to build an object file
scripts/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hotwords.dir\build.make CMakeFiles/hotwords.dir/scripts/main.cpp.obj
.PHONY : scripts/main.cpp.obj

scripts/main.i: scripts/main.cpp.i
.PHONY : scripts/main.i

# target to preprocess a source file
scripts/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hotwords.dir\build.make CMakeFiles/hotwords.dir/scripts/main.cpp.i
.PHONY : scripts/main.cpp.i

scripts/main.s: scripts/main.cpp.s
.PHONY : scripts/main.s

# target to generate assembly for a file
scripts/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hotwords.dir\build.make CMakeFiles/hotwords.dir/scripts/main.cpp.s
.PHONY : scripts/main.cpp.s

scripts/tools.obj: scripts/tools.cpp.obj
.PHONY : scripts/tools.obj

# target to build an object file
scripts/tools.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hotwords.dir\build.make CMakeFiles/hotwords.dir/scripts/tools.cpp.obj
.PHONY : scripts/tools.cpp.obj

scripts/tools.i: scripts/tools.cpp.i
.PHONY : scripts/tools.i

# target to preprocess a source file
scripts/tools.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hotwords.dir\build.make CMakeFiles/hotwords.dir/scripts/tools.cpp.i
.PHONY : scripts/tools.cpp.i

scripts/tools.s: scripts/tools.cpp.s
.PHONY : scripts/tools.s

# target to generate assembly for a file
scripts/tools.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\hotwords.dir\build.make CMakeFiles/hotwords.dir/scripts/tools.cpp.s
.PHONY : scripts/tools.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... info
	@echo ... hotwords
	@echo ... scripts/main.obj
	@echo ... scripts/main.i
	@echo ... scripts/main.s
	@echo ... scripts/tools.obj
	@echo ... scripts/tools.i
	@echo ... scripts/tools.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

